export const actionTypes = {
  SET_ITEM_INFO: `SET_ITEM_INFO`,
  SET_CURRENT_QUESTION_ID: `SET_CURRENT_QUESTION_ID`,
  SET_CURRENT_QUESTION: `SET_CURRENT_QUESTION`,
  SET_CURRENT_OPTIONS: `SET_CURRENT_OPTIONS`
}